/***************************************
	Query Passthrough su TD
	Esempio USER CODE:
	execute (
				replace view &tdStagedb..&table_target. as
				select geography_dim.*
				from &tdStagedb..geography_dim geography_dim
			
		) by teradata;
***************************************/

%macro select;
/************************************
			BEGIN USER CODE 
************************************/


execute (
        replace view &tdStagedb..&table_target. as

				SELECT  BS.REFERENCE_DT , BS.BALANCE_SHEET_SIDE ,
						BS.BS_REPORTING_CD , BS.BS_REPORTING_LINE ,
						BS.BS_ITEM_CD , BS.BS_ITEM_DESCRIPTION ,
						
						COALESCE( GR.TOT_CV_AMT , 0.0 )  AS TOT_GR , 
						COALESCE( IC.TOT_CV_AMT , 0.0 )  AS TOT_IC ,
						COALESCE(  E.TOT_CV_AMT , 0.0 )  AS TOT_EQUITY_MIN ,
						TOT_GR + TOT_IC + TOT_EQUITY_MIN AS TOTAL_NET ,
				
						COALESCE( GR.BUKT_CV_AMT_00 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_00 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_00 , 0.0 ) AS LMR_AMT_00 ,
						COALESCE( GR.BUKT_CV_AMT_01 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_01 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_01 , 0.0 ) AS LMR_AMT_01 ,
						COALESCE( GR.BUKT_CV_AMT_02 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_02 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_02 , 0.0 ) AS LMR_AMT_02 ,
						COALESCE( GR.BUKT_CV_AMT_03 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_03 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_03 , 0.0 ) AS LMR_AMT_03 ,
						COALESCE( GR.BUKT_CV_AMT_04 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_04 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_04 , 0.0 ) AS LMR_AMT_04 ,
						COALESCE( GR.BUKT_CV_AMT_05 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_05 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_05 , 0.0 ) AS LMR_AMT_05 ,
						COALESCE( GR.BUKT_CV_AMT_06 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_06 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_06 , 0.0 ) AS LMR_AMT_06 ,
						COALESCE( GR.BUKT_CV_AMT_07 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_07 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_07 , 0.0 ) AS LMR_AMT_07 ,
						COALESCE( GR.BUKT_CV_AMT_08 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_08 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_08 , 0.0 ) AS LMR_AMT_08 ,
						COALESCE( GR.BUKT_CV_AMT_09 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_09 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_09 , 0.0 ) AS LMR_AMT_09 ,
						COALESCE( GR.BUKT_CV_AMT_10 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_10 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_10 , 0.0 ) AS LMR_AMT_10 ,
						COALESCE( GR.BUKT_CV_AMT_11 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_11 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_11 , 0.0 ) AS LMR_AMT_11 ,
						COALESCE( GR.BUKT_CV_AMT_12 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_12 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_12 , 0.0 ) AS LMR_AMT_12 ,
						COALESCE( GR.BUKT_CV_AMT_13 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_13 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_13 , 0.0 ) AS LMR_AMT_13 ,
						COALESCE( GR.BUKT_CV_AMT_14 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_14 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_14 , 0.0 ) AS LMR_AMT_14 ,
						COALESCE( GR.BUKT_CV_AMT_15 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_15 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_15 , 0.0 ) AS LMR_AMT_15 ,
						COALESCE( GR.BUKT_CV_AMT_16 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_16 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_16 , 0.0 ) AS LMR_AMT_16 ,
						COALESCE( GR.BUKT_CV_AMT_17 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_17 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_17 , 0.0 ) AS LMR_AMT_17 ,
						COALESCE( GR.BUKT_CV_AMT_18 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_18 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_18 , 0.0 ) AS LMR_AMT_18 ,
						COALESCE( GR.BUKT_CV_AMT_19 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_19 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_19 , 0.0 ) AS LMR_AMT_19 ,
						COALESCE( GR.BUKT_CV_AMT_20 , 0.0 ) + COALESCE( IC.BUKT_CV_AMT_20 , 0.0 ) + COALESCE( E.BUKT_CV_AMT_20 , 0.0 ) AS LMR_AMT_20
								
						
				FROM P_KGU_LIS_SVA.USR_BALANCESHEETSCHEMA BS
				
				LEFT OUTER JOIN P_DSASVA_STG18.LIS_GROSS_AMT GR
				ON 1 = 1
				AND BS.REFERENCE_DT = GR.REFERENCE_DT
				AND BS.BS_REPORTING_CD = GR.BS_REPORTING_CD
				AND BS.BS_ITEM_CD = GR.BALANCE_SHEET_ITEM_CD
				
				
				LEFT OUTER JOIN P_DSASVA_STG18.LIS_IC IC
				ON 1 = 1
				AND BS.REFERENCE_DT = IC.REFERENCE_DT
				AND BS.BS_REPORTING_CD = IC.BS_REPORTING_CD
				AND BS.BS_ITEM_CD = IC.BALANCE_SHEET_ITEM_CD
				
				LEFT OUTER JOIN P_DSASVA_STG18.LIS_EQUITY_MIN E
				ON 1 = 1
				AND BS.REFERENCE_DT = E.REFERENCE_DT
				AND BS.BS_REPORTING_CD = E.BS_REPORTING_CD
				AND BS.BS_ITEM_CD = E.BALANCE_SHEET_ITEM_CD

    ) by teradata;




/************************************
			END USER CODE 
************************************/
%mend;