/***************************************
	Query Passthrough su TD
	Esempio USER CODE:
	execute (
				create view &tdStagedb..&lasrTable. as
				select geography_dim.*
				from &&tdStagedb..geography_dim geography_dim
			
		) by teradata;
***************************************/

%macro select;
/************************************
			BEGIN USER CODE 
************************************/

execute (
				replace view &tdStagedb..&lasrTable. /*&table_target.*/ as
select '.' "CURRENT_DATE",
       REFERENCE_DT,
       FREQ_CD,
       TEMPLATE_ROW_CD,
       TEMPLATE_ROW_DESC,
       LEGAL_ENTITY_CD,
       INTRAGROUP_COUNTERPARTY_IND,
       INTRAGROUP_COUNTERPARTY_CD,
       US_CONSOLIDATED_LE_CD,
       US_INDIVIDUAL_LE_CD,
       PERIMETER_J_FLAG,
       PERIMETER_C_FLAG,
       A.COUNTRY_CD,
       COUNTRY_DESC,
       B3_COUNTERPARTY_TYPE_CD,

       t2.BRANCH_DESC,
       t2.ASSIGNED_COUNTRY,
       t2.LIQUIDITY_REFERENCE_BANK,
       t2.CATEGORY CATEGORY_US,

       SUM(A.ACTUAL_CARRYING_VALUE) AS ACTUAL_CARRYING_VALUE, 
       SUM(A.ACTUAL_NOMINAL_VALUE) AS ACTUAL_NOMINAL_VALUE,
        SUM(A.M1) AS M1,
        SUM(A.M2 ) AS M2,
        SUM(A.M3 ) AS M3,
        SUM(A.M4 ) AS M4,
        SUM(A.M5 ) AS M5,        
        SUM(A.M6 ) AS M6,        
        SUM(A.M7 ) AS M7,        
        SUM(A.M8 ) AS M8,        
        SUM(A.M9 ) AS M9,
        SUM(A.M10 ) AS M10,
        SUM(A.M11 ) AS M11,
        SUM(A.M12 ) AS M12,
        SUM(A.M13 ) AS M13,
        SUM(A.M14 ) AS M14,
        SUM(A.M15 ) AS M15,
        SUM(A.M16) AS M16,
        SUM(A.M17 ) AS M17,
        SUM(A.M18 ) AS M18,
        SUM(A.M19 ) AS M19,
        SUM(A.M20 ) AS M20,
        SUM(A.M21 ) AS M21,
        SUM(A.M22 ) AS M22,
        SUM(A.M23 ) AS M23,
        SUM(A.M24 ) AS M24,
        SUM(A.M25 ) AS M25,
        SUM(A.M26 ) AS M26,
        SUM(A.M27 ) AS M27,
        SUM(A.M28 ) AS M28,
        SUM(A.M29 ) AS M29,
        SUM(A.M30 ) AS M30,
        SUM(A.M31 ) AS M31,
        SUM(A.M32 ) AS M32,
        SUM(A.M33) AS M33,
        SUM(A.M34) AS M34,
        SUM(A.M35) AS M35,
        SUM(A.M36) AS M36,
        SUM(A.M37) AS M37,
        SUM(A.M38) AS M38,
        SUM(A.M39) AS M39,
        SUM(A.M39toM42) AS M39toM42,
        SUM(A.M42toM45 ) AS M42toM45,
        SUM(A.M45toM48) AS M45toM48,
        SUM(A.M48toM51 ) AS M48toM51,
        SUM(A.M51to54M ) AS M51to54M,
        SUM(A.M54toM57) AS M54toM57,
        SUM(A.M57toY5 ) AS M57toY5,
        SUM(A.Y5MtoY7 ) AS Y5MtoY7,
        SUM(A.Y7toY10 ) AS Y7toY10,
        SUM(A.Y10toY15 ) AS Y10toY15,
        SUM(A.Y15toY20 ) AS Y15toY20,
        SUM(A._OVER ) AS _OVER


from ( 

SELECT DISTINCT SK_ID_NOCFL, REFERENCE_DT, SCENARIO_CD, SUBSCENARIO_CD,
        FREQ_CD, ORIGINAL_REFERENCE_DT, PROVIDER_CD, 
         FLOW_TYPE_CD, GLRT_SOURCE_CD, TEMPLATE_CD, TEMPLATE_ROW_CD,
        TEMPLATE_ROW_DESC, LEGAL_ENTITY_CD, INTRAGROUP_COUNTERPARTY_IND,
        INTRAGROUP_COUNTERPARTY_CD, FINREP_CPARTY_TYPE_CD, PERIMETER_J_FLAG,
        PERIMETER_C_FLAG, US_INDIVIDUAL_LE_CD, US_CONSOLIDATED_LE_CD,
        COUNTRY_CD, COUNTRY_DESC, ISIN_NUM, BALANCE_SHEET_ITEM_CD, REPORTING_CURRENCY_CD,
        CURRENCY_CD, B3_COUNTERPARTY_TYPE_CD, ASSET_CLASS_CD, COLLATERAL_TYPE_CD,
        CONTRACT_TYPE_CD, GUARANTEE_TYPE_CD, WTE_INSTRUMENT_TYPE_CD,
        ORIGINAL_MATURITY_CD, OPERATION_TYPE_CD, WTE_SIGN,  RETAIL_IND,
         SECURITY_TYPE_CD,
        SPEC_CREDIT_TYPE_CD, INTRAGROUP_COUNTRY_CD, INTRAGROUP_COUNTRY_DESC,
        MIN(ACTUAL_CARRYING_VALUE) AS ACTUAL_CARRYING_VALUE, 
        SUM(ACTUAL_NOMINAL_VALUE) AS ACTUAL_NOMINAL_VALUE,
        SUM(CASE WHEN MATURITY_CD='1M' THEN RUNOFF_VALUE ELSE 0 END ) AS M1,
        SUM(CASE WHEN MATURITY_CD='2M' THEN RUNOFF_VALUE ELSE 0 END ) AS M2,
        SUM(CASE WHEN MATURITY_CD='3M' THEN RUNOFF_VALUE ELSE 0 END ) AS M3,
        SUM(CASE WHEN MATURITY_CD='4M' THEN RUNOFF_VALUE ELSE 0 END ) AS M4,
        SUM(CASE WHEN MATURITY_CD='5M' THEN RUNOFF_VALUE ELSE 0 END ) AS M5,        
        SUM(CASE WHEN MATURITY_CD='6M' THEN RUNOFF_VALUE ELSE 0 END ) AS M6,        
        SUM(CASE WHEN MATURITY_CD='7M' THEN RUNOFF_VALUE ELSE 0 END ) AS M7,        
        SUM(CASE WHEN MATURITY_CD='8M' THEN RUNOFF_VALUE ELSE 0 END ) AS M8,        
        SUM(CASE WHEN MATURITY_CD='9M' THEN RUNOFF_VALUE ELSE 0 END ) AS M9,
        SUM(CASE WHEN MATURITY_CD='10M' THEN RUNOFF_VALUE ELSE 0 END ) AS M10,
        SUM(CASE WHEN MATURITY_CD='11M' THEN RUNOFF_VALUE ELSE 0 END ) AS M11,
        SUM(CASE WHEN MATURITY_CD='12M' THEN RUNOFF_VALUE ELSE 0 END ) AS M12,
        SUM(CASE WHEN MATURITY_CD='13M' THEN RUNOFF_VALUE ELSE 0 END ) AS M13,
        SUM(CASE WHEN MATURITY_CD='14M' THEN RUNOFF_VALUE ELSE 0 END ) AS M14,
        SUM(CASE WHEN MATURITY_CD='15M' THEN RUNOFF_VALUE ELSE 0 END ) AS M15,
        SUM(CASE WHEN MATURITY_CD='16M' THEN RUNOFF_VALUE ELSE 0 END ) AS M16,
        SUM(CASE WHEN MATURITY_CD='17M' THEN RUNOFF_VALUE ELSE 0 END ) AS M17,
        SUM(CASE WHEN MATURITY_CD='18M' THEN RUNOFF_VALUE ELSE 0 END ) AS M18,
        SUM(CASE WHEN MATURITY_CD='19M' THEN RUNOFF_VALUE ELSE 0 END ) AS M19,
        SUM(CASE WHEN MATURITY_CD='20M' THEN RUNOFF_VALUE ELSE 0 END ) AS M20,
        SUM(CASE WHEN MATURITY_CD='21M' THEN RUNOFF_VALUE ELSE 0 END ) AS M21,
        SUM(CASE WHEN MATURITY_CD='22M' THEN RUNOFF_VALUE ELSE 0 END ) AS M22,
        SUM(CASE WHEN MATURITY_CD='23M' THEN RUNOFF_VALUE ELSE 0 END ) AS M23,
        SUM(CASE WHEN MATURITY_CD='24M' THEN RUNOFF_VALUE ELSE 0 END ) AS M24,
        SUM(CASE WHEN MATURITY_CD='25M' THEN RUNOFF_VALUE ELSE 0 END ) AS M25,
        SUM(CASE WHEN MATURITY_CD='26M' THEN RUNOFF_VALUE ELSE 0 END ) AS M26,
        SUM(CASE WHEN MATURITY_CD='27M' THEN RUNOFF_VALUE ELSE 0 END ) AS M27,
        SUM(CASE WHEN MATURITY_CD='28M' THEN RUNOFF_VALUE ELSE 0 END ) AS M28,
        SUM(CASE WHEN MATURITY_CD='29M' THEN RUNOFF_VALUE ELSE 0 END ) AS M29,
        SUM(CASE WHEN MATURITY_CD='30M' THEN RUNOFF_VALUE ELSE 0 END ) AS M30,
        SUM(CASE WHEN MATURITY_CD='31M' THEN RUNOFF_VALUE ELSE 0 END ) AS M31,
        SUM(CASE WHEN MATURITY_CD='32M' THEN RUNOFF_VALUE ELSE 0 END ) AS M32,
        SUM(CASE WHEN MATURITY_CD='33M' THEN RUNOFF_VALUE ELSE 0 END ) AS M33,
        SUM(CASE WHEN MATURITY_CD='34M' THEN RUNOFF_VALUE ELSE 0 END ) AS M34,
        SUM(CASE WHEN MATURITY_CD='35M' THEN RUNOFF_VALUE ELSE 0 END ) AS M35,
        SUM(CASE WHEN MATURITY_CD='36M' THEN RUNOFF_VALUE ELSE 0 END ) AS M36,
        SUM(CASE WHEN MATURITY_CD='37M' THEN RUNOFF_VALUE ELSE 0 END ) AS M37,
        SUM(CASE WHEN MATURITY_CD='38M' THEN RUNOFF_VALUE ELSE 0 END ) AS M38,
        SUM(CASE WHEN MATURITY_CD='39M' THEN RUNOFF_VALUE ELSE 0 END ) AS M39,
        SUM(CASE WHEN MATURITY_CD='39Mto42M' THEN RUNOFF_VALUE ELSE 0 END ) AS M39toM42,
        SUM(CASE WHEN MATURITY_CD='42Mto45M' THEN RUNOFF_VALUE ELSE 0 END ) AS M42toM45,
        SUM(CASE WHEN MATURITY_CD='45Mto48M' THEN RUNOFF_VALUE ELSE 0 END ) AS M45toM48,
        SUM(CASE WHEN MATURITY_CD='48Mto51M' THEN RUNOFF_VALUE ELSE 0 END ) AS M48toM51,
        SUM(CASE WHEN MATURITY_CD='51Mto54M' THEN RUNOFF_VALUE ELSE 0 END ) AS M51to54M,
        SUM(CASE WHEN MATURITY_CD='54Mto57M' THEN RUNOFF_VALUE ELSE 0 END ) AS M54toM57,
        SUM(CASE WHEN MATURITY_CD='57Mto5Y' THEN RUNOFF_VALUE ELSE 0 END ) AS M57toY5,
        SUM(CASE WHEN MATURITY_CD='5YMto7Y' THEN RUNOFF_VALUE ELSE 0 END ) AS Y5MtoY7,
        SUM(CASE WHEN MATURITY_CD='7Yto10Y' THEN RUNOFF_VALUE ELSE 0 END ) AS Y7toY10,
        SUM(CASE WHEN MATURITY_CD='10Yto15Y' THEN RUNOFF_VALUE ELSE 0 END ) AS Y10toY15,
        SUM(CASE WHEN MATURITY_CD='15Yto20Y' THEN RUNOFF_VALUE ELSE 0 END ) AS Y15toY20,
        SUM(CASE WHEN MATURITY_CD='OVER' THEN RUNOFF_VALUE ELSE 0 END ) AS _OVER
 FROM P_KGU_GLM_UES.GLRT_WTE_US


GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40


) A left join P_DSASVA_STG18.US_TEC_COUNTRY_TABLE t2 
  on A.LEGAL_ENTITY_CD = t2.BRANCH_CD 


group by 
       "CURRENT_DATE",
       REFERENCE_DT,
       FREQ_CD,
       TEMPLATE_ROW_CD,
       TEMPLATE_ROW_DESC,
       LEGAL_ENTITY_CD,
       INTRAGROUP_COUNTERPARTY_IND,
       INTRAGROUP_COUNTERPARTY_CD,
       US_CONSOLIDATED_LE_CD,
       US_INDIVIDUAL_LE_CD,
       PERIMETER_J_FLAG,
       PERIMETER_C_FLAG,
       A.COUNTRY_CD,
       COUNTRY_DESC,
       B3_COUNTERPARTY_TYPE_CD,
/*
       ACTUAL_CARRYING_VALUE,
       ACTUAL_NOMINAL_VALUE,
       NOMINAL,
*/
       t2.BRANCH_DESC,
       t2.ASSIGNED_COUNTRY,
       t2.LIQUIDITY_REFERENCE_BANK,
       t2.CATEGORY


		) by teradata;







/************************************
			END USER CODE 
************************************/
%mend;